### ISSUE TITLE
Assignment Unclear: pac-3-what-is-a-test

### ISSUE THREAD

**Issue by Connereg** [learn-co-curriculum/phase-0-pac-3-what-is-a-test#2]
Thanks for raising this issue! Future learners thank you for your diligence. In
order to help the curriculum team address the problem, please use this template
to submit your feedback. We'll work on addressing the issue as soon as we can.

Please fill out as much of the information below as you can (it's ok if you
don't fill out every section). The more context we have, the easier it will be
to fix your issue!

_**Note**: you should only raise issues related to the contents of this lesson.
If you have questions about your code or need help troubleshooting, reach out to
an instructor/your peers._

---

## Link to Canvas
https://learning.flatironschool.com/courses/4706/assignments/130743?confetti=true&submitted=0Add a link to the assignment in Canvas here.

## What should be changed?

More clarity in subdivision of instructions between this assignment and the lab after it.

I believe I understand the instructions and purpose of this assignment, however it can be a bit confusing to understand what exactly to TURN IN on this page because of the unclear guidelines about what is important to do for THIS assignment and not the upcoming lab. I understand that priming the concepts used on the next page on this one is a useful strategy, but providing some bullets at the end of the page describing what should be turned in on THIS page as opposed to the next page would be helpful as I almost skipped it thinking that both pages were part of the same assignment. I manually checked the repo names against each other to be sure that they weren't which is what prompted me to turn in this assignment as it is, but this could be confusing for others without cross referencing repo titles like I did.

**Comment by ihollander** [comment]
@Connereg thanks for your feedback! I updated the [instructions](https://github.com/learn-co-curriculum/phase-0-pac-3-what-is-a-test/commit/6d22e4a5545af61de207e6a0f46d89a0ed6e8a04) in the readme on how to submit this assignment. Since you don't need to write any code to complete the assignment, all you need to submit is a link so that Canvas will mark it as complete.
