### ISSUE TITLE
Typo in actual file name.

### ISSUE THREAD

**Issue by codified45** [learn-co-curriculum/phase-0-pac-3-what-is-a-test#26]
### Canvas Link

https://learning.flatironschool.com/courses/6150/assignments/209301?module_item_id=482745

### Concern

In the part where it says:

"We have our code, now let's take a look at the tests. They are located in the test folder inside a file named index-test.js."

The file name should be written as "indexTest.js" instead of "index-test.js" to match the actual file name being referred to in the directory.  

### Suggested Changes

Fix either the text on module page, or change file name to match text, whichever is easier.

**Comment by jlboba** [comment]
Hello, thanks for bringing this issue to our attention. 

The line in the README had been fixed previously, though the change didn't get merged into your particular Canvas course. However, thanks to your issue, I did notice the file name in the index.html hadn't been. I updated that instead! 

Thank you again
