### ISSUE TITLE
No SSH option

### ISSUE THREAD

**Issue by dlinhardt15** [learn-co-curriculum/phase-0-pac-3-what-is-a-test#7]
### Canvas Link

https://learning.flatironschool.com/courses/5703/assignments/174655?module_item_id=382278

### Concern

When forking the lesson from Github, there's no SSH option for me to copy the URL in.

**Comment by professor-ben** [comment]
Use the [Pair with a TC](https://docs.google.com/document/d/1Gko5UFzCBhpo1R0V_Tx2JHSK9cRC2b_53Ky3u5Qtzlk/edit) feature in Canvas to connect with a Technical Coach on the Academic Success Team.

They should be able to hammer this out with you. If not, they'll know whether to raise it with GitHub, IT, or us to follow up on.

Thanks,
Ben
